spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sales_info
    username: postgres
    password: password
    #driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

server:
  port: 9094

sales:
  info:
    directory: C:\Users\formazione\Desktop\sales-info




